### ISSUE TITLE
Chrome Install Issue

### ISSUE THREAD

**Issue by chasekidder** [bscholer/BoilerKeyExtension#1]
In case you didn't realize, Chrome does not allow .crx files to be installed and enabled from the extension screen anymore, only from the webstore. I had to unpack it and load it as an unpacked extension in developer mode for it to work. The easy fix would be to upload it to the store.

**Comment by chasekidder** [comment]
Excellent extension though!!

**Comment by bscholer** [comment]
Thanks for letting me know! I uploaded the zip to Google drive and replaced the link on the original Reddit post.
