### ISSUE TITLE
The latest version of FireFox does not allow me to reset

### ISSUE THREAD

**Issue by blaticslm** [bscholer/BoilerKeyExtension#12]
Back to several versions of Firefox, when I click the Boilerkey Helper in the authentication page, it would pop up the "reset" button. However, when I click the button in the latest version of Firefox, it does not show up the reset button.

**Comment by bscholer** [comment]
Hi, I believe the reset feature was removed recently, so that's probably why.

There should be an update soon to fix this issue!

**Comment by bscholer** [comment]
Hi,

Sorry for this taking more than a year, but here's the new Firefox version!

https://github.com/bscholer/BoilerKeyExtension/releases/tag/v1.9.0
