### ISSUE TITLE
Extension is autofilling the wrong password

### ISSUE THREAD

**Issue by wheatly312** [bscholer/BoilerKeyExtension#13]
When attempting to log into brightspace, extension autofills the password form incorrectly. 
I have attempted to remove the extension and re-install, but this saved pin is still autofilled. I have also cleared the cache from chrome and removed any autofill password for the site.

The login page then errors out saying I have failed too many times.

Basically, I just need to go through the set up process again, but I don't see a way to get there

**Comment by bscholer** [comment]
Hi,

I've just added a reset page to the extension. It should be updated in the Chrome Web Store within a week or so, but every update is reviewed before publishing, so it's a bit of a coin toss.

Fixed in c8d40f83cb2edd6508996d7152c7cd98ac6d8368.
