### ISSUE TITLE
iOS/macOS Safari build

### ISSUE THREAD

**Issue by zyonse** [bscholer/BoilerKeyExtension#19]
- [x] Fix enrollment
- [x] Get approval for TestFlight
- [ ] Improve UX (potentially rewrite initial setup)
- [ ] Apply for App Store approval

Working on support for Safari on macOS and iOS/iPadOS. Send me an email if you'd like access to the TestFlight page.

**Comment by acvigue** [comment]
I'd like access to the TestFlight, my Apple ID email is aiden@vigue.me.

Thanks!
