### ISSUE TITLE
Does this still work as of 2023-2024 school year?

### ISSUE THREAD

**Issue by JackBlair87** [bscholer/BoilerKeyExtension#22]
I used this all last year and it was amazing. I think Purdue changed the way they do Auth at some point over the summer. Does this still work? I saw that you had commited changes three weeks ago, but the latest release to the chrome store was March 2nd. Thanks for the help!

**Comment by zyonse** [comment]
I got the username/password prompt working on the new site and cleaned up some of the credential storage functions (while also adding chrome/firefox cloud sync).

The hard part is going to be fixing the Duo mobile device activation and 2fa code autofill, I haven't had a lot of time this semester to look into it but it's definitely a priority for me to get it working again.

**Comment by JackBlair87** [comment]
Thank you for all the time you've put into this so far and I agree fixing duo activation is top priority. I think trying to get an update out before next semester would be amazing. Anything I can do to help?

**Comment by zyonse** [comment]
The duoSetup function still needs to be fixed. It stopped working at some point due to API changes.

**Comment by JackBlair87** [comment]
I have found another extension that is correctly updated. Thanks for all of you effort into this project!
https://x.com/JackBlair87/status/1744097600020615249?s=20
