### ISSUE TITLE
Firefox network error

### ISSUE THREAD

**Issue by bscholer** [bscholer/BoilerKeyExtension#3]
It seems that the activation request isn't working properly on Firefox. Does this have to do with the params being sent in the request? On each attempt, I get the following JSON back from DUO.
`{
  "readyState": 0,
  "status": 0,
  "statusText": "NetworkError: A network error occurred."
}`

Tested on Firefox on Windows and Linux, on PAL and my home network.

**Comment by nalderto** [comment]
It looks like you removed the "<all_urls>" permission while editing the manifest.json.  This is a Cross-Origin XMLHttpRequest error, and it seems Firefox is a bit more strict than Chrome when extensions POST remote domains.  I have made a pull request with the fix.

**Comment by bscholer** [comment]
Aha, thanks! I removed it because the Chrome Developer Dashboard was telling me that the permissions were too broad, so it would have to be reviewed before publishing. Turns out it didn't make a difference.
