### ISSUE TITLE
Issue setting up a new key on chrome

### ISSUE THREAD

**Issue by kcsodetz** [bscholer/BoilerKeyExtension#9]
Unable to setup a new key, (something with the api?) which results in a null value. Pasted console log screenshot below

![image](https://user-images.githubusercontent.com/22857253/64067124-68f5b200-cbf1-11e9-881f-723734841b25.png)

**Comment by hwang1607** [comment]
Having the same problem

**Comment by PallavAg** [comment]
Coming across the same issue
